### ISSUE TITLE
Intrinsic function 'concat' fails with TypeError

### ISSUE THREAD

**Issue by duelle** [xlab-si/xopera-opera#136]
Opera Version:  0.6.3.dev3

When using the intrinsic function `concat` to concatenate values:
```
topology_template:
  outputs:
    test_target:
      type: string
      value: { concat: [ get_input: test_target_hostname,
                         ":",
                         get_input: test_target_port,
                         get_input: test_target_path ] }
  inputs:
    test_target_path:
      type: string
      required: true
      default: "/"
    test_target_hostname:
      type: string
      required: true
      default: "google.com"
    test_target_port:
      type: string
      required: true
      default: 443
    test_target_use_https:
      type: string
      required: true
      default: true
```

 it results in a `TypeError`: 

```
Traceback (most recent call last):
  File "/usr/bin/opera", line 8, in <module>
    sys.exit(main())
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/cli.py", line 41, in main
    return args.func(args)
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/commands/outputs.py", line 49, in _parser_callback
    outs = outputs(storage)
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/commands/outputs.py", line 79, in outputs
    return template.get_outputs()
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/template/topology.py", line 29, in get_outputs
    return {
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/template/topology.py", line 32, in <dictcomp>
    value=v["value"].eval(self, "value"),
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/value.py", line 50, in eval
    return self.eval_function(instance)
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/value.py", line 63, in eval_function
    return getattr(instance, function_name)(params)
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/template/topology.py", line 77, in concat
    return self.join([params], node)
  File "/home/myuser/.local/lib/python3.9/site-packages/opera/template/topology.py", line 118, in join
    return delimiter.join(values_to_join)
TypeError: sequence item 2: expected str instance, int found
```

Steps to reproduce:
* Extract [todolist.csar.zip](https://github.com/xlab-si/xopera-opera/files/5652750/todolist.csar.zip)
* Run opera deployment: `AWS_ACCESS_KEY_ID=... AWS_SECRET_ACCESS_KEY=... opera deploy _definitions/radonblueprints__ServerlessToDoListAPI.tosca`
* Show outputs: `opera outputs`

**Comment by duelle** [comment]
Based on the example in section 4.3.1.3 in the TOSCA specs, https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969455

**Comment by duelle** [comment]
It looks like the port number set as a default value needs to be put in quotes to be actually treated as a string but an integer. With an input definition like the following, the error does not occur:
```
topology_template:
  outputs:
    test_target:
      type: string
      value: { concat: [ get_input: test_target_hostname,
                         ":",
                         get_input: test_target_port,
                         get_input: test_target_path ] }
  inputs:
    test_target_path:
      type: string
      required: true
      default: "/"
    test_target_hostname:
      type: string
      required: true
      default: "google.com"
    test_target_port:
      type: string
      required: true
      default: "443"
    test_target_use_https:
      type: string
      required: true
      default: true
```

**Comment by anzoman** [comment]
@duelle thanks for mentioning this and cool that you find an error that caused the problem :+1: .
